name: fuel_finder
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.7.2

dependencies:
  dartz: ^0.10.1
  dio: ^5.8.0+1
  flutter:
    sdk: flutter
  flutter_bloc: ^9.1.0
  flutter_dotenv: ^5.2.1
  flutter_map: ^8.1.1
  flutter_map_tile_caching: ^10.1.1
  flutter_native_splash: ^2.4.6
  flutter_polyline_points: ^2.1.0
  flutter_secure_storage: ^9.2.4
  font_awesome_flutter: ^10.8.0
  geocoding: ^3.0.0
  geolocator: ^14.0.0
  get_it: ^8.0.3
  http: ^1.3.0
  latlong2: ^0.9.1
  permission_handler: ^12.0.0+1
  pin_code_fields: ^8.0.1
  shared_preferences: ^2.5.3
  shimmer: ^3.0.0
  smooth_page_indicator: ^1.2.1
  cached_network_image: ^3.3.0
  path_provider: ^2.1.1
  equatable: ^2.0.5
  
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets: 
    - assets/images/
    - assets/fonts/
    - assets/icons/
    - .env
  fonts:
    - family: ProductSans
      fonts:
        - asset: assets/fonts/ProductSans-Regular.ttf
        - asset: assets/fonts/ProductSans-Bold.ttf
          weight: 700

